#! /usr/bin/env bash
#
# Date:	2024/05/06
# Author:  andyp3r3z
#
# Colorpicker utility under Wayland, with `hyprpicker`, `wl-clipboard` and `libnotify`.

color=$(hyprpicker -a)
if [[ $color ]]; then
	notify-send -i pick-colour-picker "Color Picker" "$color copied to clipboard."
fi
