#! /usr/bin/env perl

use Text::Lorem;

$num_args = $#ARGV + 1;
if ($num_args != 1) {
	print "\nUsage: lipsum <INT>\n";
	exit;
}

my $text = Text::Lorem->new();
$paragraphs = $text->paragraphs($ARGV[0]);

print $paragraphs
