#! /usr/bin/env sh
#
# Date:	2024/04/12
# Author:  andyp3r3z
#
# Changes to a random wallpaper inside a folder specified.

transitions=(any wipe wave)

while sleep $1; do
	transition=`shuf -n 1 -e "${transitions[@]}"`
	angle=`shuf -i 0-360 -n 1`
	image="$2"/`\ls "$2" | shuf -n 1`
	swww img $image --transition-type $transition --transition-angle $angle;
done
